### ISSUE TITLE
core/latte.rb:27:in `<main>': uninitialized constant Mycase (NameError)

### ISSUE THREAD

**Issue by Pandademic** [Pandademic/Latte#2]
Errors with: core/latte.rb:27:in `<main>': uninitialized constant Mycase (NameError) 😕 

**To Reproduce**
1. clone repo
2. run 'ruby core/latte.rb help'
3. See error

**Expected behavior**
error that should show:
core/latte.rb:27:in `<main>': uninitialized constant Mycase (NameError)

**or : **
1.Make a pull request
2. Link this issue
3. open in gitpod and edit

**Comment by Pandademic** [comment]
#4 could be related
