### ISSUE TITLE
command bob works for some reason

### ISSUE THREAD

**Issue by Pandademic** [Pandademic/Latte#32]
Getting /usr/lib/ruby/3.0.0/open-uri.rb:364:in `open_http': 404 Not Found (OpenURI::HTTPError) from /usr/lib/ruby/3.0.0/open-uri.rb:741:in `buffer_open' from /usr/lib/ruby/3.0.0/open-uri.rb:212:in `block in open_loop' from /usr/lib/ruby/3.0.0/open-uri.rb:210:in `catch' from /usr/lib/ruby/3.0.0/open-uri.rb:210:in `open_loop' from /usr/lib/ruby/3.0.0/open-uri.rb:151:in `open_uri' from /usr/lib/ruby/3.0.0/open-uri.rb:721:in `open' from /usr/lib/ruby/3.0.0/open-uri.rb:29:in `open' from /home/dada/Latte/core/latte.rb:15:in `getPkgfile' from /home/dada/Latte/core/latte.rb:11:in `findPkg' from /home/dada/Latte/core/latte.rb:43:in `<main>'

**Comment by Pandademic** [comment]
The error above means there is no such package

**Comment by Pandademic** [comment]
The bug here is that is trying to do latte add

**Comment by Pandademic** [comment]
closed due to being stale
